# Generated by Django 3.0 on 2020-08-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_consult'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlytarot',
            name='color',
            field=models.CharField(default='white', max_length=50),
        ),
        migrations.AddField(
            model_name='yearlytarot',
            name='crystal',
            field=models.CharField(default='diamond', max_length=50),
        ),
        migrations.AddField(
            model_name='yearlytarot',
            name='zodiac',
            field=models.CharField(choices=[('Aries', 'Aries'), ('Taurus', 'Taurus'), ('Gemini', 'Gemini'), ('Cancer', 'Cancer'), ('Leo', 'Leo'), ('Virgo', 'Virgo'), ('Libra', 'Libra'), ('Scorpio', 'Scorpio'), ('Sagittarius', 'Sagittarius'), ('Capricorn', 'Capricorn'), ('Aquarius', 'Aquarius'), ('Pisces', 'Pisces')], default='Aries', max_length=50),
        ),
    ]
