# Generated by Django 3.0 on 2020-08-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20200812_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChineseZodiac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images')),
                ('zodiac', models.CharField(choices=[('Rat', 'Rat'), ('Ox', 'Ox'), ('Tiger', 'Tiger'), ('Rabbit', 'Rabbit'), ('Dragon', 'Dragon'), ('Snake', 'Snake'), ('Horse', 'Horse'), ('Goat', 'Goat'), ('Monkey', 'Monkey'), ('Rooster', 'Rooster'), ('Dog', 'Dog'), ('Pig', 'Pig')], max_length=20)),
                ('chars', models.TextField()),
                ('years', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Festivals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('f_date', models.DateField()),
                ('f_time', models.TimeField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KundliMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('birth_date', models.DateField()),
                ('birth_time', models.TimeField()),
                ('birth_place', models.CharField(max_length=50)),
                ('p_name', models.CharField(max_length=100)),
                ('p_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('p_birth_date', models.DateField()),
                ('p_birth_time', models.TimeField()),
                ('p_birth_place', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PalmReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('left_palm', models.ImageField(upload_to='')),
                ('right_palm', models.ImageField(upload_to='')),
            ],
        ),
    ]
