# Generated by Django 3.0 on 2020-08-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_chinesezodiac_festivals_kundlimatch_palmreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
