# Generated by Django 3.0 on 2020-08-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_babynames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarotquestion',
            name='post',
        ),
    ]
