# Generated by Django 3.0 on 2020-08-12 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_tarotquestion_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarotAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TarotQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='PalmReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('palm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PalmReading')),
            ],
        ),
    ]
